### ISSUE TITLE
Hardcoded reference to `app/public` is also too broad

### ISSUE THREAD

**Issue by joffotron** [rubyatscale/rubocop-packs#71]
Referring to https://github.com/rubyatscale/rubocop-packs/blob/main/lib/rubocop/cop/packs/class_methods_as_public_apis.rb#L42

As an example of where the cop is checking for the path of the pack's public API.

We also have a directory at `app/public_helpers` which is not for public use, but this cop is picking it up due to the use of `.include?` here.

We can use a different name in the meantime, but it would be good if this check could be a bit more specific, or even better, be based off the `public_path:` config in package.yml

Cheers :)

**Comment by alexevanczuk** [comment]
Thanks for opening the issue! Yeah, this should definitely check the pack configured path if it exists, cc @professor! 

If you're feeling up to it, feel free to send a PR 👍🏼

**Comment by professor** [comment]
We've merged a PR that tightens the regex. This should have solved the problem for you. 

If you'd like to see a better solution relying on `public_path` , then feel free to create a PR.
